version: '3'

services:
  mongodb:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017
    ports:
      - "8080:8080"
